languages: go

go:
  - "1.10.x"

branches:
  only:
    - master

before_install:
  - mv $HOME/build/fuwalab $GOPATH/src/
  - mkdir -p $GOPATH/src/github.com/fuwalab
  - cp -r $GOPATH/src/tools $GOPATH/src/github.com/fuwalab/

install:
  - go get -t ./...
  - rm -rf $GOPATH/src/github.com/fuwalab/*
  - cp -r $GOPATH/src/tools $GOPATH/src/github.com/fuwalab/

script:
  - go test -v ./...

notifications:
  email: false
