env:
  global:
    - CC_TEST_REPORTER_ID=461d7447d1f3e5024607936c0c5d199583a488525a54b2bc44fc93b51b93486d

languages: go

go:
  - "1.10.x"

branches:
  only:
    - master

before_install:
  - mv $HOME/build/fuwalab $GOPATH/src/

install:
  - go get -t ./...
  - rm -rf $GOPATH/src/github.com/fuwalab/*
  - cp -r $GOPATH/src/tools $GOPATH/src/github.com/fuwalab/

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  #- go test -v ./...
  - go test -coverprofile c.out -v ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
